import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: appTarget.targetName,
    projects: [
        "App",
        "CLI",
        "Shared",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: Version(26, 4, 0)
    )
)
