import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: appTarget.targetName,
    projects: [
        "App",
        "CLI",
        "Shared",
    ],
    schemes: [
        .scheme(
            name: "iCLI-Release",
            shared: true,
            buildAction: .buildAction(targets: [
                .project(path: "App", target: "iCLI"),
                .project(path: "CLI", target: "icli"),
            ]),
            archiveAction: .archiveAction(configuration: "Release")
        )
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: Version(26, 4, 0)
    )
)
